version: '3.8'

services:
  # Architecture
  nginx:
    image: nginx:bookworm
    network_mode: host
    restart: unless-stopped
    volumes:
      - './docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'

  ngrok:
    image: ngrok/ngrok:debian
    network_mode: host
    restart: unless-stopped
    command:
      - 'start'
      - '--all'
      - '--config'
      - '/etc/authtoken.yml'
      - '--config'
      - '/etc/ngrok.yml'
      - '--log'
      - 'stdout'
    volumes:
      - './docker/ngrok/etc/authtoken.yml:/etc/authtoken.yml'
      - './docker/ngrok/etc/ngrok.yml:/etc/ngrok.yml'

  db:
    image: postgres:15.3-bookworm
    network_mode: host
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local